{
  repository(owner: "_REPO_OWNER_", name: "_REPO_NAME_") {
    issues(first: 100, filterBy: {since: "2022-01-01T00:00:00Z"}) {
      totalCount
      edges {
        cursor
        node {
          number
          title
          createdAt
          state
          closedAt
          updatedAt
          url
          labels(first: 100) {
            edges {
              node {
                name
              }
            }
          }
          timelineItems(first: 100, itemTypes: [CROSS_REFERENCED_EVENT, ISSUE_COMMENT, CLOSED_EVENT]) {
            totalCount
            edges {
              node {
                ... on CrossReferencedEvent {
                  source {
                    ... on Issue {
                      __typename
                      number
                      closed
                    }
                    ... on PullRequest {
                      __typename
                      number
                      closed
                    }
                  }
                  isCrossRepository
                }
                ... on IssueComment {
                  author {
                    login
                  }
                  createdAt
                }
                ... on ClosedEvent {
                  actor {
                    login
                  }
                }
              }
            }
          } 
        }
      }
    }
  }
}

