query {                                                                         
  repository(owner:"numpy", name:"numpy") {                                     
    issues(first:100 states:OPEN) {                                             
      edges {                                                                   
        node {
          number
          title
          createdAt
          timelineItems(first:20, itemTypes:CROSS_REFERENCED_EVENT){            
            totalCount 
            edges{
              node{
                ... on CrossReferencedEvent {
                  source{
                    ... on Issue {
                      __typename
                      number
                      closed
                    }
                  ... on PullRequest {
                    __typename
                    number
                    closed
                  }
                  }
                  isCrossRepository
                }
              }
            }
          }                                                                     
        }                                                                       
      }                                                                         
    }                                                                           
  }                                                                             
}
