query {                                                                        
  repository(owner:"numpy", name:"numpy") {                                     
    issues(first:100 states:OPEN) {
      totalCount
      edges {
        cursor
        node {
          number
          title
          createdAt
          url
          timelineItems(first:100, itemTypes:CROSS_REFERENCED_EVENT){            
            totalCount                                                          
          }                                                                     
        }                                                                       
      }                                                                         
    }                                                                           
  }                                                                             
}
